### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by sqc2290318555** [TUMFTM/truckscenes-devkit#3]
How could i download this dataset?

**Comment by ffent** [comment]
Hi @sqc2290318555,

thanks for your interest in our work. The dataset will soon become available and will be downloadable via our website.

**Comment by Kin-Zhang** [comment]
Still not available.... Waiting for the new.

**Comment by ffent** [comment]
Hi @Kin-Zhang ,

we are very sorry for letting all of you wait for so long and working hard to get the dataset online as soon as possible. The good news is that we are almost there. You can actually track our progress on this [pull request](https://github.com/awslabs/open-data-registry/pull/2417) to the AWS Open Data Registry.

**Comment by ffent** [comment]
We just released a mini version of the dataset until to full version becomes available.

**Comment by wpqmanu** [comment]
> We just released a mini version of the dataset until to full version becomes available.

The website says “This link is expired and cannot be used anymore.” Could you kindly update the link? Thanks a lot.

**Comment by ffent** [comment]
Dear all,

We are very happy to announce that the full dataset is now available on our website 🎉

Please check out [www.man.eu/truckscenes](www.man.eu/truckscenes) to download MAN TruckScenes.

We are excited to enable your applications.
