### ISSUE TITLE
Error in the unzipping instruction on website

### ISSUE THREAD

**Issue by chris-23** [TUMFTM/truckscenes-devkit#6]
In the [Download instructions](https://brandportal.man/d/QSf8mPdU5Hgj/downloads#/-/dataset) for the dataset there is a small error:
`unzip man-truckscenes_*.zip` 
should be
`unzip "man-truckscenes_*.zip"` to avoid bash expanding the *.

Also, we realized a potential issue when downloading the dataset. If a wget command fails to download a part of the data the unzip part would still extract all existing data, but the dataset would be not complete. Also when a wget command fails and you just repeat that command, wget would create a zip.1 file and not overwrite the file. So a user should manually remove the failed download before retrying. Maybe you can add a short note in the description regarding that

**Comment by ffent** [comment]
Hi @chris-23,

thanks for reporting this potential error. We will adjust the instructions on the website and provide checksums to verify the downloaded files.

**Comment by ffent** [comment]
md5 checksums were added to validate the downloaded files.
