### ISSUE TITLE
CAN bus data

### ISSUE THREAD

**Issue by alfredgu001324** [TUMFTM/truckscenes-devkit#7]
Thank you for releasing such an interesting dataset! I am wondering whether a CAN bus expansion would be released as well similar to nuscenes that include steering, throttle etc. low level information?

**Comment by ffent** [comment]
Hi @alfredgu001324,

thanks for your question and your interest in our MAN TruckScenes dataset. A CAN bus expansion is currently not planned, but we will collect such requests and consider them in discussions for future expansions.
